development:
  adapter: postgresql
  encoding: unicode
  database: onemonth_development
  host: localhost
  pool: 5
  username: action
  password:
  
test:
  adapter: postgresql
  encoding: unicode
  database: onemonth_test
  host: localhost
  pool: 5
  username: action
  password:
  
production:
  adapter: postgresql
  encoding: unicode
  database: onemonth_production
  host: localhost
  pool: 5
  username: action
  password: 
  
