# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 221698e8705376a68bed1e8e3fede33f7dea8c993bfe732dde660e6fdda264488c6c7de07ef913c2aaf29e0ce05057b6466178615de541ee52e56588dff19ea3

test:
  secret_key_base: 235f6773fb54a5c6315eca5dd70ed9055597765d202151572b74218d6271bc7ff293d3d3815ed313703e305ab882e09940a9832b11a272b57c0d3feb3742f608

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
